baseURL: "http://example.org/"
languageCode: "de-de"
title: "COVID19 Video Platform"
DefaultContentLanguage: "de"

author: ""
canonifyurls: true
languagecode: "de"
theme: "black-and-light"

params:
  sitename: "COVID19 Video Platform"
  APIURL: "https://api.example.com"


languages:
  en:
    languageName: "[EN]"
    menu:
      main:
      - name: About
        url: /about/
        weight: 1
      - name: Create Appointment
        url: /new-appointment/
        weight: 2
      - name: List Appointments
        url: /appointments/
        weight: 3
      - name: Status
        url: /status/
        weight: 4
      footer:
      - name: Privacy
        url: /privacy/
        weight: 5
      - name: Imprint
        url: /imprint/
        weight: 6   
  de:
    languageName: "[DE]"
    menu:
      main:
      - name: über das Projekt
        url: /about/
        weight: 1
      - name: Termin erstellen
        url: /new-appointment/
        weight: 2
      - name: Übersicht Termine
        url: /appointments/
        weight: 3
      - name: Status
        url: /status/
        weight: 4
      footer:
      - name: Datenschutz
        url: /privacy/
        weight: 5
      - name: Impressum
        url: /imprint/
        weight: 6